import { Prompt } from '@/types';

export const mockPrompts: Prompt[] = [
  {
    id: '1',
    title: '원피스 스타일',
    description: '사진을 원피스 만화 스타일로 변환',
    beforeImageUrl: '/dummy/before-1.svg',
    afterImageUrl: '/dummy/after-1.svg',
    promptText: 'Style transfer: Apply One Piece manga\nart style. Maintain character_features(\nexpression, pose, composition ).\nAdd bold_outlines, vibrant_colors,\nmanga_screen_tone effects.',
    copyCount: 1250,
    createdAt: '2024-05-01',
    category: 'hot',
  },
  {
    id: '2',
    title: '나루토 스타일',
    description: '닌자 만화 스타일로 변환',
    beforeImageUrl: '/dummy/before-2.svg',
    afterImageUrl: '/dummy/after-2.svg',
    promptText: 'Ninja style transformation: Apply Naruto\nanime aesthetics. Use high_contrast,\ndynamic_shadows, and ninja_elements.\nEnsure character_anatomy is preserved\nwith cel-shaded coloring.',
    copyCount: 2300,
    createdAt: '2024-05-02',
    category: 'hot',
  },
  {
    id: '3',
    title: '코난 스타일',
    description: '명탐정 코난 그림체로',
    beforeImageUrl: '/dummy/before-3.svg',
    afterImageUrl: '/dummy/after-3.svg',
    promptText: 'Detective style: Apply Case Closed\n(Detective Conan) art style. Focus on\nsharp_chin_lines, large_expressive_eyes,\nand simple_vibrant_shading.',
    copyCount: 850,
    createdAt: '2024-05-03',
    category: 'new',
  },
  {
    id: '4',
    title: '블리치 스타일',
    description: '블리치 스타일 캐릭터로',
    beforeImageUrl: '/dummy/before-4.svg',
    afterImageUrl: '/dummy/after-4.svg',
    promptText: 'Soul Reaper style: Apply Bleach manga\naesthetics. Emphasize sharp_edges,\nheavy_inks, and cool_color_palettes.\nAdd atmospheric_reishi_effects.',
    copyCount: 450,
    createdAt: '2024-05-04',
    category: 'all',
  },
  {
    id: '5',
    title: '지브리 스타일',
    description: '미야자키 하야오 풍 일러스트',
    beforeImageUrl: '/dummy/before-5.svg',
    afterImageUrl: '/dummy/after-5.svg',
    promptText: 'Studio Ghibli aesthetic: Soft_lighting,\npastel_colors, and detailed_nature.\nApply hand-painted_watercolor_look\nwith nostalgic_atmosphere.',
    copyCount: 4800,
    createdAt: '2024-05-05',
    category: 'hot',
  },
  {
    id: '6',
    title: '리그오브레전드 스타일',
    description: 'LoL 챔피언 일러스트 풍',
    beforeImageUrl: '/dummy/before-6.svg',
    afterImageUrl: '/dummy/after-6.svg',
    promptText: 'League of Legends splash art: High_fantasy,\ndynamic_poses, and epic_lighting.\nDetailed_textures with magical_glow\nand cinematic_composition.',
    copyCount: 150,
    createdAt: '2024-05-06',
    category: 'new',
  },
  {
    id: '7',
    title: '오버워치 스타일',
    description: '오버워치 캐릭터 풍',
    beforeImageUrl: '/dummy/before-7.svg',
    afterImageUrl: '/dummy/after-7.svg',
    promptText: 'Overwatch character style: Stylized_3D_render,\nclean_lines, and bright_saturated_colors.\nSci-fi_elements with heroic_lighting\nand smooth_surfaces.',
    copyCount: 320,
    createdAt: '2024-05-07',
    category: 'new',
  },
  {
    id: '8',
    title: '사이버펑크 스타일',
    description: '2077년 네온 도시 캐릭터',
    beforeImageUrl: '/dummy/before-8.svg',
    afterImageUrl: '/dummy/after-8.svg',
    promptText: 'Cyberpunk 2077 aesthetic: Neon_lights,\nrainy_night_atmosphere, and high-tech_details.\nStrong_contrast between pink/cyan\nand dark_shadows.',
    copyCount: 3500,
    createdAt: '2024-05-08',
    category: 'hot',
  },
  {
    id: '9',
    title: '수채화 스타일',
    description: '부드러운 수채화 그림으로',
    beforeImageUrl: '/dummy/before-9.svg',
    afterImageUrl: '/dummy/after-9.svg',
    promptText: 'Soft watercolor painting: Blurred_edges,\nvisible_paper_texture, and bleeding_colors.\nDreamy_atmosphere with light_washes\nof pastel_tones.',
    copyCount: 920,
    createdAt: '2024-05-09',
    category: 'all',
  },
  {
    id: '10',
    title: '픽셀 아트 스타일',
    description: '8비트 게임 픽셀 아트',
    beforeImageUrl: '/dummy/before-10.svg',
    afterImageUrl: '/dummy/after-10.svg',
    promptText: 'Retro 8-bit pixel art: Limited_palette,\nsharp_pixels, and dithered_shading.\nClassic_gaming_aesthetic with\nchibi_character_proportions.',
    copyCount: 1100,
    createdAt: '2024-05-10',
    category: 'all',
  },
  {
    id: '11',
    title: '수묵화 스타일',
    description: '동양 전통 수묵화 풍경',
    beforeImageUrl: '/dummy/before-11.svg',
    afterImageUrl: '/dummy/after-11.svg',
    promptText: 'Traditional Ink Wash: Sumi-e style,\nbold_brush_strokes, and negative_space.\nMonochromatic_ink_bleed with\nzen_minimalist_composition.',
    copyCount: 280,
    createdAt: '2024-05-11',
    category: 'new',
  },
  {
    id: '12',
    title: '유화 초상화 스타일',
    description: '르네상스 시대 유화처럼',
    beforeImageUrl: '/dummy/before-12.svg',
    afterImageUrl: '/dummy/after-12.svg',
    promptText: 'Renaissance oil painting: Chiaroscuro_lighting,\nrich_earthy_tones, and visible_impasto.\nClassical_portrait_composition with\ndramatic_depth.',
    copyCount: 650,
    createdAt: '2024-05-12',
    category: 'all',
  },
];

export const getMockPrompts = (): Prompt[] => mockPrompts;

export const getMockPromptById = (id: string): Prompt | null => 
  mockPrompts.find(p => p.id === id) || null;

export const getMockPromptsByCategory = (category: 'new' | 'hot' | 'all'): Prompt[] => {
  if (category === 'all') return mockPrompts;
  return mockPrompts.filter(p => p.category === category);
};
